"(14, 6)" = [(3, 1.0, (0, 0))]
"(14, 7)" = [(3, 0.85, (0, 0)), (8, 0.15, (4, 4))]
"(9, 6)" = [(6, 1.0, (3, 2))]
"(5, 5)" = [(5, 0.2, (2, 1)), (6, 0.65, (9, 2)), (7, 0.15, (2, 3))]
"(19, 8)" = [(3, 0.9, (0, 0)), (4, 0.1, (0, 5))]
"(14, 8)" = [(3, 0.45, (0, 0)), (8, 0.5, (4, 4)), (4, 0.05, (0, 5))]
"(9, 5)" = [(3, 0.8, (0, 0)), (7, 0.2, (3, 3))]
"(9, 7)" = [(7, 0.85, (3, 3)), (8, 0.15, (3, 4))]





["agegrp_1"]
["agegrp_1"."(14, 6)"]
   ["agegrp_1"."(14, 6)".to_7] 
          tocond = 7
          pr = 1.0 
          next = "(0, 0)"
["agegrp_1"."(14,7)"]
  ["agegrp_1"."(14,7)".to_7]      
              tocond = 7 
              pr = 0.85 
              next = "(0, 0)" 
  ["agegrp_1"."(14,7)".to_8]    
             tocond = 8
             pr =  0.15
             next = "(4, 4)"
