# send_risk must be as long as the number of lags--we like 25
send_risk = [0.0, 0.3, 0.65, 0.75, 0.85, 0.85, 0.75, 0.7, 0.65, 0.6, 
			 0.5, 0.2, 0.1, 0.1, 0.1, 0.05, 0.05, 0.0, 0.0, 0.0, 
			 0.0, 0.0, 0.0, 0.0, 0.0]

# recv_risk must have 5 entries between 0.0 and 1.0
recv_risk = [0.1, 0.39, 0.44, 0.54, 0.56]

# contact_factors and touch_factors reshaped after loaded 
# to look like the arrangements below
	# size(contact_factors) to (4,5) => input in TOML is (20, ) made to look 4 x 5
	# size(touch_factors) to (6,5) => input in TOML is (30,) made to look 6 x 5

contact_factors =       [ 1.1,    2.0,    2.0,     1.6,   1.0,    # nil
                          1.1,    1.9,    1.9,     1.5,   0.9,    # mild
                          0.7,    1.0,    1.0,     0.7,   0.6,    # sick
                          0.5,    0.6,    0.6,     0.5,   0.5]    # severe
#              # agegrp    1       2       3        4       5
touch_factors =         [0.55,   0.62,    0.60,    0.4,   0.35,   # unexposed
                         0.55,   0.62,    0.60,    0.4,   0.35,   # recovered
                         0.55,   0.62,    0.60,    0.4,   0.35,   # nil
                         0.55,   0.62,    0.55 ,   0.4,   0.28,   # mild
                         0.28,   0.35,    0.3,     0.18,  0.18,   # sick
                         0.18,   0.18,    0.18,   0.18,   0.18]   # severe