[1]

[[1."[5,5]"]]
next = [9, 5]
pr = 0.4
tocond = 5

[[1."[5,5]"]]
next = [9, 6]
pr = 0.5
tocond = 6

[[1."[5,5]"]]
next = [9, 7]
pr = 0.1
tocond = 7

[[1."[9,5]"]]
next = [0, 0]
pr = 0.9
tocond = 3

[[1."[9,5]"]]
next = [14, 7]
pr = 0.1
tocond = 7

[[1."[9,6]"]]
next = [14, 6]
pr = 1.0
tocond = 6

[[1."[9,7]"]]
next = [14, 7]
pr = 0.95
tocond = 7

[[1."[9,7]"]]
next = [14, 8]
pr = 0.05
tocond = 8

[[1."[14,6]"]]
next = [0, 0]
pr = 1.0
tocond = 3

[[1."[14,7]"]]
next = [0, 0]
pr = 0.85
tocond = 3

[[1."[14,7]"]]
next = [25, 7]
pr = 0.12
tocond = 7

[[1."[14,7]"]]
next = [19, 8]
pr = 0.03
tocond = 8

[[1."[14,8]"]]
next = [0, 0]
pr = 0.692
tocond = 3

[[1."[14,8]"]]
next = [19, 8]
pr = 0.302
tocond = 8

[[1."[14,8]"]]
next = [0, 5]
pr = 0.006
tocond = 4

[[1."[19,8]"]]
next = [0, 0]
pr = 0.891
tocond = 3

[[1."[19,8]"]]
next = [25, 8]
pr = 0.106
tocond = 8

[[1."[19,8]"]]
next = [0, 5]
pr = 0.003
tocond = 4

[[1."[25,7]"]]
next = [0, 0]
pr = 0.976
tocond = 3

[[1."[25,7]"]]
next = [0, 5]
pr = 0.024
tocond = 4

[[1."[25,8]"]]
next = [0, 0]
pr = 0.91
tocond = 3

[[1."[25,8]"]]
next = [0, 5]
pr = 0.09
tocond = 4

[2]

[[2."[5,5]"]]
next = [9, 5]
pr = 0.2
tocond = 5

[[2."[5,5]"]]
next = [9, 6]
pr = 0.7
tocond = 6

[[2."[5,5]"]]
next = [9, 7]
pr = 0.1
tocond = 7

[[2."[9,5]"]]
next = [0, 0]
pr = 0.85
tocond = 3

[[2."[9,5]"]]
next = [14, 7]
pr = 0.15
tocond = 7

[[2."[9,6]"]]
next = [14, 6]
pr = 1.0
tocond = 6

[[2."[9,7]"]]
next = [14, 7]
pr = 0.9
tocond = 7

[[2."[9,7]"]]
next = [14, 8]
pr = 0.1
tocond = 8

[[2."[14,6]"]]
next = [0, 0]
pr = 1.0
tocond = 3

[[2."[14,7]"]]
next = [0, 0]
pr = 0.83
tocond = 3

[[2."[14,7]"]]
next = [25, 7]
pr = 0.1
tocond = 7

[[2."[14,7]"]]
next = [19, 8]
pr = 0.07
tocond = 8

[[2."[14,8]"]]
next = [0, 0]
pr = 0.474
tocond = 3

[[2."[14,8]"]]
next = [19, 8]
pr = 0.514
tocond = 8

[[2."[14,8]"]]
next = [0, 5]
pr = 0.012
tocond = 4

[[2."[19,8]"]]
next = [0, 0]
pr = 0.922
tocond = 3

[[2."[19,8]"]]
next = [25, 8]
pr = 0.072
tocond = 8

[[2."[19,8]"]]
next = [0, 5]
pr = 0.006
tocond = 4

[[2."[25,7]"]]
next = [0, 0]
pr = 0.964
tocond = 3

[[2."[25,7]"]]
next = [0, 5]
pr = 0.036
tocond = 4

[[2."[25,8]"]]
next = [0, 0]
pr = 0.964
tocond = 3

[[2."[25,8]"]]
next = [0, 5]
pr = 0.036
tocond = 4

[3]

[[3."[5,5]"]]
next = [9, 5]
pr = 0.2
tocond = 5

[[3."[5,5]"]]
next = [9, 6]
pr = 0.7
tocond = 6

[[3."[5,5]"]]
next = [9, 7]
pr = 0.1
tocond = 7

[[3."[9,5]"]]
next = [0, 0]
pr = 0.9
tocond = 3

[[3."[9,5]"]]
next = [14, 7]
pr = 0.1
tocond = 7

[[3."[9,6]"]]
next = [14, 6]
pr = 1.0
tocond = 6

[[3."[9,7]"]]
next = [14, 7]
pr = 0.9
tocond = 7

[[3."[9,7]"]]
next = [14, 8]
pr = 0.1
tocond = 8

[[3."[14,6]"]]
next = [0, 0]
pr = 0.9
tocond = 3

[[3."[14,6]"]]
next = [25, 7]
pr = 0.1
tocond = 7

[[3."[14,7]"]]
next = [0, 0]
pr = 0.85
tocond = 3

[[3."[14,7]"]]
next = [25, 7]
pr = 0.14
tocond = 7

[[3."[14,7]"]]
next = [19, 8]
pr = 0.01
tocond = 8

[[3."[14,8]"]]
next = [0, 0]
pr = 0.776
tocond = 3

[[3."[14,8]"]]
next = [19, 8]
pr = 0.206
tocond = 8

[[3."[14,8]"]]
next = [0, 5]
pr = 0.018
tocond = 4

[[3."[19,8]"]]
next = [0, 0]
pr = 0.856
tocond = 3

[[3."[19,8]"]]
next = [25, 8]
pr = 0.126
tocond = 8

[[3."[19,8]"]]
next = [0, 5]
pr = 0.018
tocond = 4

[[3."[25,7]"]]
next = [0, 0]
pr = 0.958
tocond = 3

[[3."[25,7]"]]
next = [0, 5]
pr = 0.042
tocond = 4

[[3."[25,8]"]]
next = [0, 0]
pr = 0.958
tocond = 3

[[3."[25,8]"]]
next = [0, 5]
pr = 0.042
tocond = 4

[4]

[[4."[5,5]"]]
next = [9, 5]
pr = 0.15
tocond = 5

[[4."[5,5]"]]
next = [9, 6]
pr = 0.6
tocond = 6

[[4."[5,5]"]]
next = [9, 7]
pr = 0.25
tocond = 7

[[4."[9,5]"]]
next = [0, 0]
pr = 0.62
tocond = 3

[[4."[9,5]"]]
next = [14, 7]
pr = 0.38
tocond = 7

[[4."[9,6]"]]
next = [14, 6]
pr = 1.0
tocond = 6

[[4."[9,7]"]]
next = [14, 7]
pr = 0.78
tocond = 7

[[4."[9,7]"]]
next = [14, 8]
pr = 0.22
tocond = 8

[[4."[14,6]"]]
next = [0, 0]
pr = 1.0
tocond = 3

[[4."[14,7]"]]
next = [0, 0]
pr = 0.8
tocond = 3

[[4."[14,7]"]]
next = [25, 7]
pr = 0.1
tocond = 7

[[4."[14,7]"]]
next = [19, 8]
pr = 0.1
tocond = 8

[[4."[14,8]"]]
next = [0, 0]
pr = 0.165
tocond = 3

[[4."[14,8]"]]
next = [19, 8]
pr = 0.715
tocond = 8

[[4."[14,8]"]]
next = [0, 5]
pr = 0.12
tocond = 4

[[4."[19,8]"]]
next = [0, 0]
pr = 0.81
tocond = 3

[[4."[19,8]"]]
next = [25, 8]
pr = 0.13
tocond = 8

[[4."[19,8]"]]
next = [0, 5]
pr = 0.06
tocond = 4

[[4."[25,7]"]]
next = [0, 0]
pr = 0.76
tocond = 3

[[4."[25,7]"]]
next = [0, 5]
pr = 0.24
tocond = 4

[[4."[25,8]"]]
next = [0, 0]
pr = 0.688
tocond = 3

[[4."[25,8]"]]
next = [0, 5]
pr = 0.312
tocond = 4

[5]

[[5."[5,5]"]]
next = [9, 5]
pr = 0.1
tocond = 5

[[5."[5,5]"]]
next = [9, 6]
pr = 0.5
tocond = 6

[[5."[5,5]"]]
next = [9, 7]
pr = 0.4
tocond = 7

[[5."[9,5]"]]
next = [0, 0]
pr = 0.5
tocond = 3

[[5."[9,5]"]]
next = [14, 7]
pr = 0.5
tocond = 7

[[5."[9,6]"]]
next = [14, 6]
pr = 0.4
tocond = 6

[[5."[9,6]"]]
next = [14, 7]
pr = 0.6
tocond = 7

[[5."[9,7]"]]
next = [14, 7]
pr = 0.6
tocond = 7

[[5."[9,7]"]]
next = [14, 8]
pr = 0.4
tocond = 8

[[5."[14,6]"]]
next = [0, 0]
pr = 0.7
tocond = 3

[[5."[14,6]"]]
next = [25, 7]
pr = 0.3
tocond = 7

[[5."[14,7]"]]
next = [0, 0]
pr = 0.7
tocond = 3

[[5."[14,7]"]]
next = [25, 7]
pr = 0.1
tocond = 7

[[5."[14,7]"]]
next = [19, 8]
pr = 0.2
tocond = 8

[[5."[14,8]"]]
next = [0, 0]
pr = 0.12
tocond = 3

[[5."[14,8]"]]
next = [19, 8]
pr = 0.67
tocond = 8

[[5."[14,8]"]]
next = [0, 5]
pr = 0.21
tocond = 4

[[5."[19,8]"]]
next = [0, 0]
pr = 0.49
tocond = 3

[[5."[19,8]"]]
next = [25, 8]
pr = 0.24
tocond = 8

[[5."[19,8]"]]
next = [0, 5]
pr = 0.27
tocond = 4

[[5."[25,7]"]]
next = [0, 0]
pr = 0.682
tocond = 3

[[5."[25,7]"]]
next = [0, 5]
pr = 0.318
tocond = 4

[[5."[25,8]"]]
next = [0, 0]
pr = 0.676
tocond = 3

[[5."[25,8]"]]
next = [0, 5]
pr = 0.324
tocond = 4
